# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1414, 824)
        MainWindow.setStyleSheet("\n"
"      /*\n"
"      Ubuntu Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Company: GTRONICK\n"
"Last updated: 01/10/2021 (dd/mm/yyyy), 15:18.\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/Ubuntu.qss\n"
"*/\n"
"QMainWindow {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QCheckBox {\n"
"    padding:2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border:1px solid rgb(255,150,60);\n"
"    border-radius:4px;\n"
"    padding: 1px;\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(190, 90, 50, 50), stop:1 rgba(250, 130, 40, 50));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border:1px solid rgb(246, 134, 86);\n"
"    border-radius:4px;\n"
"      background-color:rgb(246, 134, 86)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-width:1px solid rgb(246, 134, 86);\n"
"    border-radius:4px;\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QColorDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox:editable {\n"
"    selection-color:rgb(81,72,65);\n"
"    selection-background-color: #ffffff;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    selection-color: #ffffff;\n"
"    selection-background-color: rgb(246, 134, 86);\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color:  #1e1d23;    \n"
"}\n"
"QDateTimeEdit, QDateEdit, QDoubleSpinBox, QFontComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"\n"
"QLabel,QLineEdit {\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QLineEdit {\n"
"    background-color:rgb(255,255,255);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QMenuBar {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item {\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"    padding-right:2px;\n"
"    border-top-width:2px;\n"
"    border-left-width:2px;\n"
"    border-right-width:2px;\n"
"    border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-style:solid;\n"
"    background-color:rgb(65,64,59);\n"
"    border-top-color: rgb(47,47,44);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"}\n"
"QMenu {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    padding:4px 10px 4px 20px;\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style:solid;\n"
"    border-width:3px;\n"
"    padding:4px 7px 4px 17px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border: 1px solid transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px inset rgb(150,150,150); \n"
"    border-radius: 10px;\n"
"    background-color:rgb(221,221,219);\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border:1px solid;\n"
"    border-radius:8px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPushButton{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-bottom-color: rgb(150,150,150);\n"
"    border-right-color: rgb(165,165,165);\n"
"    border-left-color: rgb(165,165,165);\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-style: solid;\n"
"    padding: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:default{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-width: 1px;\n"
"    border-top-color: rgba(255,150,60,200);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-bottom-color: rgba(200,70,20,200);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    color:rgb(174,167,159);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(230, 230, 230, 255));\n"
"}\n"
"QRadioButton {\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgba(246, 134, 86, 255);\n"
"    color: #a9b7c6;\n"
"    background-color:rgba(246, 134, 86, 255);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollArea {\n"
"    color: white;\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QSlider::groove {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal, QSlider::add-page:vertical {\n"
"     background: white;\n"
"}\n"
"QSlider::sub-page:horizontal, QSlider::sub-page:vertical {\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QStatusBar, QSpinBox {\n"
"    color:rgb(81,72,65);\n"
"}\n"
"QSpinBox {\n"
"    background-color: #ffffff;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"      border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"      border-bottom-left-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    border: 1px transparent grey;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"} \n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid;\n"
"    border-color: rgb(207,207,207);\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-bottom-right-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"     height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"      border: 1px transparent grey;\n"
"      border-bottom-left-radius: 3px;\n"
"      border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: rgb(180,180,180);\n"
"    background-color:rgb(247,246,246);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    padding-bottom:2px;\n"
"    padding-top:2px;\n"
"    color:rgb(81,72,65);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(221,218,217,255), stop:1 rgba(240,239,238,255));\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-left-color: rgb(180,180,180);\n"
"    border-right-color: rgb(180,180,180);\n"
"    border-bottom-color: transparent;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(247,246,246);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"    margin-right: 1px;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QTimeEdit, QToolBox, QToolBox::tab, QToolBox::tab:selected {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"    ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.grpbx_multWindow = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpbx_multWindow.sizePolicy().hasHeightForWidth())
        self.grpbx_multWindow.setSizePolicy(sizePolicy)
        self.grpbx_multWindow.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.grpbx_multWindow.setFont(font)
        self.grpbx_multWindow.setObjectName("grpbx_multWindow")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.grpbx_multWindow)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.wgt_multWindow_amp = QtWidgets.QWidget(self.grpbx_multWindow)
        self.wgt_multWindow_amp.setObjectName("wgt_multWindow_amp")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.wgt_multWindow_amp)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.lbl_amplitude_3 = QtWidgets.QLabel(self.wgt_multWindow_amp)
        self.lbl_amplitude_3.setObjectName("lbl_amplitude_3")
        self.gridLayout_16.addWidget(self.lbl_amplitude_3, 1, 0, 1, 1)
        self.lbl_value_amp_3 = QtWidgets.QLabel(self.wgt_multWindow_amp)
        self.lbl_value_amp_3.setObjectName("lbl_value_amp_3")
        self.gridLayout_16.addWidget(self.lbl_value_amp_3, 2, 1, 1, 1)
        self.slider_amplitude_2 = QtWidgets.QSlider(self.wgt_multWindow_amp)
        self.slider_amplitude_2.setMinimum(1)
        self.slider_amplitude_2.setMaximum(100)
        self.slider_amplitude_2.setProperty("value", 100)
        self.slider_amplitude_2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_amplitude_2.setInvertedAppearance(False)
        self.slider_amplitude_2.setObjectName("slider_amplitude_2")
        self.gridLayout_16.addWidget(self.slider_amplitude_2, 2, 0, 1, 1)
        self.gridLayout_17.addWidget(self.wgt_multWindow_amp, 5, 0, 1, 2)
        self.plot_multWindow = PlotWidget(self.grpbx_multWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.plot_multWindow.sizePolicy().hasHeightForWidth())
        self.plot_multWindow.setSizePolicy(sizePolicy)
        self.plot_multWindow.setMinimumSize(QtCore.QSize(0, 50))
        self.plot_multWindow.setBaseSize(QtCore.QSize(0, 1))
        self.plot_multWindow.setObjectName("plot_multWindow")
        self.gridLayout_17.addWidget(self.plot_multWindow, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.grpbx_multWindow)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_17.addWidget(self.line, 3, 0, 1, 2)
        self.cmbx_multWindow = QtWidgets.QComboBox(self.grpbx_multWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbx_multWindow.sizePolicy().hasHeightForWidth())
        self.cmbx_multWindow.setSizePolicy(sizePolicy)
        self.cmbx_multWindow.setMinimumSize(QtCore.QSize(100, 25))
        self.cmbx_multWindow.setMaximumSize(QtCore.QSize(120, 30))
        self.cmbx_multWindow.setBaseSize(QtCore.QSize(0, 0))
        self.cmbx_multWindow.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cmbx_multWindow.setObjectName("cmbx_multWindow")
        self.cmbx_multWindow.addItem("")
        self.cmbx_multWindow.addItem("")
        self.cmbx_multWindow.addItem("")
        self.cmbx_multWindow.addItem("")
        self.gridLayout_17.addWidget(self.cmbx_multWindow, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.grpbx_multWindow, 4, 0, 1, 1)
        self.wgt_sliders = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sliders.sizePolicy().hasHeightForWidth())
        self.wgt_sliders.setSizePolicy(sizePolicy)
        self.wgt_sliders.setMaximumSize(QtCore.QSize(16777215, 300))
        self.wgt_sliders.setObjectName("wgt_sliders")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wgt_sliders)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lbl_gain = QtWidgets.QLabel(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_gain.sizePolicy().hasHeightForWidth())
        self.lbl_gain.setSizePolicy(sizePolicy)
        self.lbl_gain.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gain.setObjectName("lbl_gain")
        self.verticalLayout_12.addWidget(self.lbl_gain)
        self.lbl_gain_max = QtWidgets.QLabel(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_gain_max.sizePolicy().hasHeightForWidth())
        self.lbl_gain_max.setSizePolicy(sizePolicy)
        self.lbl_gain_max.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gain_max.setObjectName("lbl_gain_max")
        self.verticalLayout_12.addWidget(self.lbl_gain_max)
        self.lbl_gain_zero = QtWidgets.QLabel(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_gain_zero.sizePolicy().hasHeightForWidth())
        self.lbl_gain_zero.setSizePolicy(sizePolicy)
        self.lbl_gain_zero.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gain_zero.setObjectName("lbl_gain_zero")
        self.verticalLayout_12.addWidget(self.lbl_gain_zero)
        self.lbl_gain_min = QtWidgets.QLabel(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_gain_min.sizePolicy().hasHeightForWidth())
        self.lbl_gain_min.setSizePolicy(sizePolicy)
        self.lbl_gain_min.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_gain_min.setObjectName("lbl_gain_min")
        self.verticalLayout_12.addWidget(self.lbl_gain_min)
        self.lbl_freqs = QtWidgets.QLabel(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_freqs.sizePolicy().hasHeightForWidth())
        self.lbl_freqs.setSizePolicy(sizePolicy)
        self.lbl_freqs.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_freqs.setObjectName("lbl_freqs")
        self.verticalLayout_12.addWidget(self.lbl_freqs)
        self.btn_reset_sliders = QtWidgets.QPushButton(self.wgt_sliders)
        self.btn_reset_sliders.setObjectName("btn_reset_sliders")
        self.verticalLayout_12.addWidget(self.btn_reset_sliders)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.wgt_sld_1 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_1.sizePolicy().hasHeightForWidth())
        self.wgt_sld_1.setSizePolicy(sizePolicy)
        self.wgt_sld_1.setObjectName("wgt_sld_1")
        self.gridLayout = QtWidgets.QGridLayout(self.wgt_sld_1)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.lnEdit_gain_slider_1 = QtWidgets.QLineEdit(self.wgt_sld_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_1.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_1.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_1.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_1.setReadOnly(True)
        self.lnEdit_gain_slider_1.setObjectName("lnEdit_gain_slider_1")
        self.gridLayout.addWidget(self.lnEdit_gain_slider_1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.slider1 = QtWidgets.QSlider(self.wgt_sld_1)
        self.slider1.setMinimum(-30)
        self.slider1.setMaximum(30)
        self.slider1.setSingleStep(1)
        self.slider1.setProperty("value", 0)
        self.slider1.setOrientation(QtCore.Qt.Vertical)
        self.slider1.setObjectName("slider1")
        self.verticalLayout.addWidget(self.slider1, 0, QtCore.Qt.AlignHCenter)
        self.label_slider1 = QtWidgets.QLabel(self.wgt_sld_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider1.sizePolicy().hasHeightForWidth())
        self.label_slider1.setSizePolicy(sizePolicy)
        self.label_slider1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider1.setObjectName("label_slider1")
        self.verticalLayout.addWidget(self.label_slider1)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.lnEdit_freq_slider_1 = QtWidgets.QLineEdit(self.wgt_sld_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_1.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_1.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_1.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_1.setInputMask("")
        self.lnEdit_freq_slider_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_1.setReadOnly(True)
        self.lnEdit_freq_slider_1.setObjectName("lnEdit_freq_slider_1")
        self.gridLayout.addWidget(self.lnEdit_freq_slider_1, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.wgt_sld_1, 0, 1, 1, 1)
        self.wgt_sld_2 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_2.sizePolicy().hasHeightForWidth())
        self.wgt_sld_2.setSizePolicy(sizePolicy)
        self.wgt_sld_2.setObjectName("wgt_sld_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.wgt_sld_2)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.slider2 = QtWidgets.QSlider(self.wgt_sld_2)
        self.slider2.setMinimum(-30)
        self.slider2.setMaximum(30)
        self.slider2.setSingleStep(1)
        self.slider2.setProperty("value", 0)
        self.slider2.setOrientation(QtCore.Qt.Vertical)
        self.slider2.setObjectName("slider2")
        self.verticalLayout_2.addWidget(self.slider2, 0, QtCore.Qt.AlignHCenter)
        self.label_slider2 = QtWidgets.QLabel(self.wgt_sld_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider2.sizePolicy().hasHeightForWidth())
        self.label_slider2.setSizePolicy(sizePolicy)
        self.label_slider2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider2.setObjectName("label_slider2")
        self.verticalLayout_2.addWidget(self.label_slider2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.lnEdit_freq_slider_2 = QtWidgets.QLineEdit(self.wgt_sld_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_2.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_2.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_2.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_2.setInputMask("")
        self.lnEdit_freq_slider_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_2.setReadOnly(True)
        self.lnEdit_freq_slider_2.setObjectName("lnEdit_freq_slider_2")
        self.gridLayout_3.addWidget(self.lnEdit_freq_slider_2, 2, 0, 1, 1)
        self.lnEdit_gain_slider_2 = QtWidgets.QLineEdit(self.wgt_sld_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_2.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_2.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_2.setReadOnly(True)
        self.lnEdit_gain_slider_2.setObjectName("lnEdit_gain_slider_2")
        self.gridLayout_3.addWidget(self.lnEdit_gain_slider_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.wgt_sld_2, 0, 2, 1, 1)
        self.wgt_sld_3 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_3.sizePolicy().hasHeightForWidth())
        self.wgt_sld_3.setSizePolicy(sizePolicy)
        self.wgt_sld_3.setObjectName("wgt_sld_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wgt_sld_3)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.slider3 = QtWidgets.QSlider(self.wgt_sld_3)
        self.slider3.setMinimum(-30)
        self.slider3.setMaximum(30)
        self.slider3.setSingleStep(1)
        self.slider3.setProperty("value", 0)
        self.slider3.setOrientation(QtCore.Qt.Vertical)
        self.slider3.setObjectName("slider3")
        self.verticalLayout_3.addWidget(self.slider3, 0, QtCore.Qt.AlignHCenter)
        self.label_slider3 = QtWidgets.QLabel(self.wgt_sld_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider3.sizePolicy().hasHeightForWidth())
        self.label_slider3.setSizePolicy(sizePolicy)
        self.label_slider3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider3.setObjectName("label_slider3")
        self.verticalLayout_3.addWidget(self.label_slider3)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.lnEdit_freq_slider_3 = QtWidgets.QLineEdit(self.wgt_sld_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_3.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_3.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_3.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_3.setInputMask("")
        self.lnEdit_freq_slider_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_3.setReadOnly(True)
        self.lnEdit_freq_slider_3.setObjectName("lnEdit_freq_slider_3")
        self.gridLayout_4.addWidget(self.lnEdit_freq_slider_3, 2, 0, 1, 1)
        self.lnEdit_gain_slider_3 = QtWidgets.QLineEdit(self.wgt_sld_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_3.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_3.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_3.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_3.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_3.setReadOnly(True)
        self.lnEdit_gain_slider_3.setObjectName("lnEdit_gain_slider_3")
        self.gridLayout_4.addWidget(self.lnEdit_gain_slider_3, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.wgt_sld_3, 0, 3, 1, 1)
        self.wgt_sld_4 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_4.sizePolicy().hasHeightForWidth())
        self.wgt_sld_4.setSizePolicy(sizePolicy)
        self.wgt_sld_4.setObjectName("wgt_sld_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.wgt_sld_4)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.slider4 = QtWidgets.QSlider(self.wgt_sld_4)
        self.slider4.setMinimum(-30)
        self.slider4.setMaximum(30)
        self.slider4.setSingleStep(1)
        self.slider4.setProperty("value", 0)
        self.slider4.setOrientation(QtCore.Qt.Vertical)
        self.slider4.setObjectName("slider4")
        self.verticalLayout_4.addWidget(self.slider4, 0, QtCore.Qt.AlignHCenter)
        self.label_slider4 = QtWidgets.QLabel(self.wgt_sld_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider4.sizePolicy().hasHeightForWidth())
        self.label_slider4.setSizePolicy(sizePolicy)
        self.label_slider4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider4.setObjectName("label_slider4")
        self.verticalLayout_4.addWidget(self.label_slider4)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.lnEdit_freq_slider_4 = QtWidgets.QLineEdit(self.wgt_sld_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_4.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_4.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_4.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_4.setInputMask("")
        self.lnEdit_freq_slider_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_4.setReadOnly(True)
        self.lnEdit_freq_slider_4.setObjectName("lnEdit_freq_slider_4")
        self.gridLayout_5.addWidget(self.lnEdit_freq_slider_4, 2, 0, 1, 1)
        self.lnEdit_gain_slider_4 = QtWidgets.QLineEdit(self.wgt_sld_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_4.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_4.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_4.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_4.setReadOnly(True)
        self.lnEdit_gain_slider_4.setObjectName("lnEdit_gain_slider_4")
        self.gridLayout_5.addWidget(self.lnEdit_gain_slider_4, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.wgt_sld_4, 0, 4, 1, 1)
        self.wgt_sld_5 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_5.sizePolicy().hasHeightForWidth())
        self.wgt_sld_5.setSizePolicy(sizePolicy)
        self.wgt_sld_5.setObjectName("wgt_sld_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.wgt_sld_5)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.slider5 = QtWidgets.QSlider(self.wgt_sld_5)
        self.slider5.setMinimum(-30)
        self.slider5.setMaximum(30)
        self.slider5.setSingleStep(1)
        self.slider5.setProperty("value", 0)
        self.slider5.setOrientation(QtCore.Qt.Vertical)
        self.slider5.setObjectName("slider5")
        self.verticalLayout_5.addWidget(self.slider5, 0, QtCore.Qt.AlignHCenter)
        self.label_slider5 = QtWidgets.QLabel(self.wgt_sld_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider5.sizePolicy().hasHeightForWidth())
        self.label_slider5.setSizePolicy(sizePolicy)
        self.label_slider5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider5.setObjectName("label_slider5")
        self.verticalLayout_5.addWidget(self.label_slider5)
        self.gridLayout_6.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.lnEdit_freq_slider_5 = QtWidgets.QLineEdit(self.wgt_sld_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_5.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_5.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_5.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_5.setInputMask("")
        self.lnEdit_freq_slider_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_5.setReadOnly(True)
        self.lnEdit_freq_slider_5.setObjectName("lnEdit_freq_slider_5")
        self.gridLayout_6.addWidget(self.lnEdit_freq_slider_5, 2, 0, 1, 1)
        self.lnEdit_gain_slider_5 = QtWidgets.QLineEdit(self.wgt_sld_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_5.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_5.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_5.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_5.setReadOnly(True)
        self.lnEdit_gain_slider_5.setObjectName("lnEdit_gain_slider_5")
        self.gridLayout_6.addWidget(self.lnEdit_gain_slider_5, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.wgt_sld_5, 0, 5, 1, 1)
        self.wgt_sld_6 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_6.sizePolicy().hasHeightForWidth())
        self.wgt_sld_6.setSizePolicy(sizePolicy)
        self.wgt_sld_6.setObjectName("wgt_sld_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.wgt_sld_6)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.slider6 = QtWidgets.QSlider(self.wgt_sld_6)
        self.slider6.setMinimum(-30)
        self.slider6.setMaximum(30)
        self.slider6.setSingleStep(1)
        self.slider6.setProperty("value", 0)
        self.slider6.setOrientation(QtCore.Qt.Vertical)
        self.slider6.setObjectName("slider6")
        self.verticalLayout_6.addWidget(self.slider6, 0, QtCore.Qt.AlignHCenter)
        self.label_slider6 = QtWidgets.QLabel(self.wgt_sld_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider6.sizePolicy().hasHeightForWidth())
        self.label_slider6.setSizePolicy(sizePolicy)
        self.label_slider6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider6.setObjectName("label_slider6")
        self.verticalLayout_6.addWidget(self.label_slider6)
        self.gridLayout_7.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.lnEdit_freq_slider_6 = QtWidgets.QLineEdit(self.wgt_sld_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_6.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_6.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_6.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_6.setInputMask("")
        self.lnEdit_freq_slider_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_6.setReadOnly(True)
        self.lnEdit_freq_slider_6.setObjectName("lnEdit_freq_slider_6")
        self.gridLayout_7.addWidget(self.lnEdit_freq_slider_6, 2, 0, 1, 1)
        self.lnEdit_gain_slider_6 = QtWidgets.QLineEdit(self.wgt_sld_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_6.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_6.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_6.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_6.setReadOnly(True)
        self.lnEdit_gain_slider_6.setObjectName("lnEdit_gain_slider_6")
        self.gridLayout_7.addWidget(self.lnEdit_gain_slider_6, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.wgt_sld_6, 0, 6, 1, 1)
        self.wgt_sld_7 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_7.sizePolicy().hasHeightForWidth())
        self.wgt_sld_7.setSizePolicy(sizePolicy)
        self.wgt_sld_7.setObjectName("wgt_sld_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.wgt_sld_7)
        self.gridLayout_8.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.slider7 = QtWidgets.QSlider(self.wgt_sld_7)
        self.slider7.setMinimum(-30)
        self.slider7.setMaximum(30)
        self.slider7.setSingleStep(1)
        self.slider7.setProperty("value", 0)
        self.slider7.setOrientation(QtCore.Qt.Vertical)
        self.slider7.setObjectName("slider7")
        self.verticalLayout_7.addWidget(self.slider7, 0, QtCore.Qt.AlignHCenter)
        self.label_slider7 = QtWidgets.QLabel(self.wgt_sld_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider7.sizePolicy().hasHeightForWidth())
        self.label_slider7.setSizePolicy(sizePolicy)
        self.label_slider7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider7.setObjectName("label_slider7")
        self.verticalLayout_7.addWidget(self.label_slider7)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.lnEdit_freq_slider_7 = QtWidgets.QLineEdit(self.wgt_sld_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_7.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_7.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_7.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_7.setInputMask("")
        self.lnEdit_freq_slider_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_7.setReadOnly(True)
        self.lnEdit_freq_slider_7.setObjectName("lnEdit_freq_slider_7")
        self.gridLayout_8.addWidget(self.lnEdit_freq_slider_7, 2, 0, 1, 1)
        self.lnEdit_gain_slider_7 = QtWidgets.QLineEdit(self.wgt_sld_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_7.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_7.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_7.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_7.setReadOnly(True)
        self.lnEdit_gain_slider_7.setObjectName("lnEdit_gain_slider_7")
        self.gridLayout_8.addWidget(self.lnEdit_gain_slider_7, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.wgt_sld_7, 0, 7, 1, 1)
        self.wgt_sld_8 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_8.sizePolicy().hasHeightForWidth())
        self.wgt_sld_8.setSizePolicy(sizePolicy)
        self.wgt_sld_8.setObjectName("wgt_sld_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.wgt_sld_8)
        self.gridLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.slider8 = QtWidgets.QSlider(self.wgt_sld_8)
        self.slider8.setMinimum(-30)
        self.slider8.setMaximum(30)
        self.slider8.setSingleStep(1)
        self.slider8.setProperty("value", 0)
        self.slider8.setOrientation(QtCore.Qt.Vertical)
        self.slider8.setObjectName("slider8")
        self.verticalLayout_8.addWidget(self.slider8, 0, QtCore.Qt.AlignHCenter)
        self.label_slider8 = QtWidgets.QLabel(self.wgt_sld_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider8.sizePolicy().hasHeightForWidth())
        self.label_slider8.setSizePolicy(sizePolicy)
        self.label_slider8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider8.setObjectName("label_slider8")
        self.verticalLayout_8.addWidget(self.label_slider8)
        self.gridLayout_9.addLayout(self.verticalLayout_8, 1, 0, 1, 1)
        self.lnEdit_freq_slider_8 = QtWidgets.QLineEdit(self.wgt_sld_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_8.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_8.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_8.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_8.setInputMask("")
        self.lnEdit_freq_slider_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_8.setReadOnly(True)
        self.lnEdit_freq_slider_8.setObjectName("lnEdit_freq_slider_8")
        self.gridLayout_9.addWidget(self.lnEdit_freq_slider_8, 2, 0, 1, 1)
        self.lnEdit_gain_slider_8 = QtWidgets.QLineEdit(self.wgt_sld_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_8.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_8.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_8.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_8.setReadOnly(True)
        self.lnEdit_gain_slider_8.setObjectName("lnEdit_gain_slider_8")
        self.gridLayout_9.addWidget(self.lnEdit_gain_slider_8, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.wgt_sld_8, 0, 8, 1, 1)
        self.wgt_sld_9 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_9.sizePolicy().hasHeightForWidth())
        self.wgt_sld_9.setSizePolicy(sizePolicy)
        self.wgt_sld_9.setObjectName("wgt_sld_9")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.wgt_sld_9)
        self.gridLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.slider9 = QtWidgets.QSlider(self.wgt_sld_9)
        self.slider9.setMinimum(-30)
        self.slider9.setMaximum(30)
        self.slider9.setSingleStep(1)
        self.slider9.setProperty("value", 0)
        self.slider9.setOrientation(QtCore.Qt.Vertical)
        self.slider9.setObjectName("slider9")
        self.verticalLayout_9.addWidget(self.slider9, 0, QtCore.Qt.AlignHCenter)
        self.label_slider9 = QtWidgets.QLabel(self.wgt_sld_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider9.sizePolicy().hasHeightForWidth())
        self.label_slider9.setSizePolicy(sizePolicy)
        self.label_slider9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider9.setObjectName("label_slider9")
        self.verticalLayout_9.addWidget(self.label_slider9)
        self.gridLayout_10.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.lnEdit_freq_slider_9 = QtWidgets.QLineEdit(self.wgt_sld_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_9.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_9.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_9.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_9.setInputMask("")
        self.lnEdit_freq_slider_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_9.setReadOnly(True)
        self.lnEdit_freq_slider_9.setObjectName("lnEdit_freq_slider_9")
        self.gridLayout_10.addWidget(self.lnEdit_freq_slider_9, 2, 0, 1, 1)
        self.lnEdit_gain_slider_9 = QtWidgets.QLineEdit(self.wgt_sld_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_9.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_9.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_9.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_9.setReadOnly(True)
        self.lnEdit_gain_slider_9.setObjectName("lnEdit_gain_slider_9")
        self.gridLayout_10.addWidget(self.lnEdit_gain_slider_9, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.wgt_sld_9, 0, 9, 1, 1)
        self.wgt_sld_10 = QtWidgets.QWidget(self.wgt_sliders)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wgt_sld_10.sizePolicy().hasHeightForWidth())
        self.wgt_sld_10.setSizePolicy(sizePolicy)
        self.wgt_sld_10.setObjectName("wgt_sld_10")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.wgt_sld_10)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.slider10 = QtWidgets.QSlider(self.wgt_sld_10)
        self.slider10.setMinimum(-30)
        self.slider10.setMaximum(30)
        self.slider10.setSingleStep(1)
        self.slider10.setProperty("value", 0)
        self.slider10.setTracking(True)
        self.slider10.setOrientation(QtCore.Qt.Vertical)
        self.slider10.setObjectName("slider10")
        self.verticalLayout_10.addWidget(self.slider10, 0, QtCore.Qt.AlignHCenter)
        self.label_slider10 = QtWidgets.QLabel(self.wgt_sld_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider10.sizePolicy().hasHeightForWidth())
        self.label_slider10.setSizePolicy(sizePolicy)
        self.label_slider10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_slider10.setObjectName("label_slider10")
        self.verticalLayout_10.addWidget(self.label_slider10)
        self.gridLayout_11.addLayout(self.verticalLayout_10, 1, 0, 1, 1)
        self.lnEdit_freq_slider_10 = QtWidgets.QLineEdit(self.wgt_sld_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_freq_slider_10.sizePolicy().hasHeightForWidth())
        self.lnEdit_freq_slider_10.setSizePolicy(sizePolicy)
        self.lnEdit_freq_slider_10.setMinimumSize(QtCore.QSize(75, 0))
        self.lnEdit_freq_slider_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_freq_slider_10.setInputMask("")
        self.lnEdit_freq_slider_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_freq_slider_10.setReadOnly(True)
        self.lnEdit_freq_slider_10.setObjectName("lnEdit_freq_slider_10")
        self.gridLayout_11.addWidget(self.lnEdit_freq_slider_10, 2, 0, 1, 1)
        self.lnEdit_gain_slider_10 = QtWidgets.QLineEdit(self.wgt_sld_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lnEdit_gain_slider_10.sizePolicy().hasHeightForWidth())
        self.lnEdit_gain_slider_10.setSizePolicy(sizePolicy)
        self.lnEdit_gain_slider_10.setMinimumSize(QtCore.QSize(50, 0))
        self.lnEdit_gain_slider_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lnEdit_gain_slider_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lnEdit_gain_slider_10.setReadOnly(True)
        self.lnEdit_gain_slider_10.setObjectName("lnEdit_gain_slider_10")
        self.gridLayout_11.addWidget(self.lnEdit_gain_slider_10, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addWidget(self.wgt_sld_10, 0, 10, 1, 1)
        self.gridLayout_12.addWidget(self.wgt_sliders, 4, 2, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_rewind_input = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rewind_input.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/restart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_rewind_input.setIcon(icon)
        self.btn_rewind_input.setObjectName("btn_rewind_input")
        self.horizontalLayout.addWidget(self.btn_rewind_input)
        self.btn_pan_left_input = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pan_left_input.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/fastBackward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pan_left_input.setIcon(icon1)
        self.btn_pan_left_input.setObjectName("btn_pan_left_input")
        self.horizontalLayout.addWidget(self.btn_pan_left_input)
        self.btn_play_input = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play_input.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_play_input.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_play_input.setIcon(icon2)
        self.btn_play_input.setCheckable(True)
        self.btn_play_input.setObjectName("btn_play_input")
        self.horizontalLayout.addWidget(self.btn_play_input)
        self.btn_pan_right_input = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pan_right_input.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/skipforward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pan_right_input.setIcon(icon3)
        self.btn_pan_right_input.setObjectName("btn_pan_right_input")
        self.horizontalLayout.addWidget(self.btn_pan_right_input)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_zoom_in = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_in.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_in.setIcon(icon4)
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.horizontalLayout_3.addWidget(self.btn_zoom_in)
        self.btn_zoom_out = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zoom_out.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_out.setIcon(icon5)
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.horizontalLayout_3.addWidget(self.btn_zoom_out)
        self.slider_speed = QtWidgets.QSlider(self.centralwidget)
        self.slider_speed.setMinimum(1)
        self.slider_speed.setMaximum(20)
        self.slider_speed.setPageStep(5)
        self.slider_speed.setProperty("value", 10)
        self.slider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_speed.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.slider_speed.setTickInterval(2)
        self.slider_speed.setObjectName("slider_speed")
        self.horizontalLayout_3.addWidget(self.slider_speed)
        self.lbl_speed = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_speed.sizePolicy().hasHeightForWidth())
        self.lbl_speed.setSizePolicy(sizePolicy)
        self.lbl_speed.setScaledContents(True)
        self.lbl_speed.setObjectName("lbl_speed")
        self.horizontalLayout_3.addWidget(self.lbl_speed)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_rewind_output = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rewind_output.setText("")
        self.btn_rewind_output.setIcon(icon)
        self.btn_rewind_output.setObjectName("btn_rewind_output")
        self.horizontalLayout_2.addWidget(self.btn_rewind_output)
        self.btn_pan_left_output = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pan_left_output.setText("")
        self.btn_pan_left_output.setIcon(icon1)
        self.btn_pan_left_output.setObjectName("btn_pan_left_output")
        self.horizontalLayout_2.addWidget(self.btn_pan_left_output)
        self.btn_play_output = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play_output.setText("")
        self.btn_play_output.setIcon(icon2)
        self.btn_play_output.setCheckable(True)
        self.btn_play_output.setObjectName("btn_play_output")
        self.horizontalLayout_2.addWidget(self.btn_play_output)
        self.btn_pan_right_output = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pan_right_output.setText("")
        self.btn_pan_right_output.setIcon(icon3)
        self.btn_pan_right_output.setObjectName("btn_pan_right_output")
        self.horizontalLayout_2.addWidget(self.btn_pan_right_output)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout_12.addLayout(self.horizontalLayout_4, 2, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_12.addWidget(self.line_2, 3, 0, 1, 3)
        self.cmbx_mode_selection = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbx_mode_selection.sizePolicy().hasHeightForWidth())
        self.cmbx_mode_selection.setSizePolicy(sizePolicy)
        self.cmbx_mode_selection.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbx_mode_selection.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.cmbx_mode_selection.setObjectName("cmbx_mode_selection")
        self.cmbx_mode_selection.addItem("")
        self.cmbx_mode_selection.addItem("")
        self.cmbx_mode_selection.addItem("")
        self.cmbx_mode_selection.addItem("")
        self.gridLayout_12.addWidget(self.cmbx_mode_selection, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.grpbx_input = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.grpbx_input.setFont(font)
        self.grpbx_input.setObjectName("grpbx_input")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.grpbx_input)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.plot_input_sig_spect = PlotWidget(self.grpbx_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_input_sig_spect.sizePolicy().hasHeightForWidth())
        self.plot_input_sig_spect.setSizePolicy(sizePolicy)
        self.plot_input_sig_spect.setObjectName("plot_input_sig_spect")
        self.gridLayout_14.addWidget(self.plot_input_sig_spect, 1, 1, 1, 1)
        self.plot_input_sig_freq = PlotWidget(self.grpbx_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_input_sig_freq.sizePolicy().hasHeightForWidth())
        self.plot_input_sig_freq.setSizePolicy(sizePolicy)
        self.plot_input_sig_freq.setObjectName("plot_input_sig_freq")
        self.gridLayout_14.addWidget(self.plot_input_sig_freq, 1, 0, 1, 1)
        self.plot_input_sig_time = PlotWidget(self.grpbx_input)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_input_sig_time.sizePolicy().hasHeightForWidth())
        self.plot_input_sig_time.setSizePolicy(sizePolicy)
        self.plot_input_sig_time.setObjectName("plot_input_sig_time")
        self.gridLayout_14.addWidget(self.plot_input_sig_time, 0, 0, 1, 2)
        self.horizontalLayout_8.addWidget(self.grpbx_input)
        self.grpbx_output = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.grpbx_output.setFont(font)
        self.grpbx_output.setObjectName("grpbx_output")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.grpbx_output)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.plot_output_sig_freq = PlotWidget(self.grpbx_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_output_sig_freq.sizePolicy().hasHeightForWidth())
        self.plot_output_sig_freq.setSizePolicy(sizePolicy)
        self.plot_output_sig_freq.setObjectName("plot_output_sig_freq")
        self.gridLayout_15.addWidget(self.plot_output_sig_freq, 1, 0, 1, 1)
        self.plot_output_sig_spect = PlotWidget(self.grpbx_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_output_sig_spect.sizePolicy().hasHeightForWidth())
        self.plot_output_sig_spect.setSizePolicy(sizePolicy)
        self.plot_output_sig_spect.setObjectName("plot_output_sig_spect")
        self.gridLayout_15.addWidget(self.plot_output_sig_spect, 1, 1, 1, 1)
        self.plot_output_sig_time = PlotWidget(self.grpbx_output)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_output_sig_time.sizePolicy().hasHeightForWidth())
        self.plot_output_sig_time.setSizePolicy(sizePolicy)
        self.plot_output_sig_time.setObjectName("plot_output_sig_time")
        self.gridLayout_15.addWidget(self.plot_output_sig_time, 0, 0, 1, 2)
        self.horizontalLayout_8.addWidget(self.grpbx_output)
        self.gridLayout_12.addLayout(self.horizontalLayout_8, 1, 0, 1, 3)
        self.chkbx_spect = QtWidgets.QCheckBox(self.centralwidget)
        self.chkbx_spect.setMinimumSize(QtCore.QSize(100, 0))
        self.chkbx_spect.setObjectName("chkbx_spect")
        self.gridLayout_12.addWidget(self.chkbx_spect, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1414, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionOpen.setShortcutVisibleInContextMenu(True)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSave.setShortcutVisibleInContextMenu(True)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.grpbx_multWindow.setTitle(_translate("MainWindow", "Multiplication Window"))
        self.lbl_amplitude_3.setText(_translate("MainWindow", "Standard Deviation"))
        self.lbl_value_amp_3.setText(_translate("MainWindow", "100"))
        self.cmbx_multWindow.setItemText(0, _translate("MainWindow", "Rectangle"))
        self.cmbx_multWindow.setItemText(1, _translate("MainWindow", "Hamming"))
        self.cmbx_multWindow.setItemText(2, _translate("MainWindow", "Hanning"))
        self.cmbx_multWindow.setItemText(3, _translate("MainWindow", "Gaussian"))
        self.lbl_gain.setText(_translate("MainWindow", "Gain"))
        self.lbl_gain_max.setText(_translate("MainWindow", "max: 30 dB"))
        self.lbl_gain_zero.setText(_translate("MainWindow", "init: 0 dB"))
        self.lbl_gain_min.setText(_translate("MainWindow", "min: -30 dB"))
        self.lbl_freqs.setText(_translate("MainWindow", "Frequency"))
        self.btn_reset_sliders.setText(_translate("MainWindow", "Reset"))
        self.lnEdit_gain_slider_1.setText(_translate("MainWindow", "0"))
        self.label_slider1.setText(_translate("MainWindow", "Slider 1"))
        self.lnEdit_freq_slider_1.setText(_translate("MainWindow", "0"))
        self.label_slider2.setText(_translate("MainWindow", "Slider 2"))
        self.lnEdit_freq_slider_2.setText(_translate("MainWindow", "0"))
        self.lnEdit_gain_slider_2.setText(_translate("MainWindow", "0"))
        self.label_slider3.setText(_translate("MainWindow", "Slider 3"))
        self.lnEdit_freq_slider_3.setText(_translate("MainWindow", "0"))
        self.lnEdit_gain_slider_3.setText(_translate("MainWindow", "0"))
        self.label_slider4.setText(_translate("MainWindow", "Slider 4"))
        self.lnEdit_freq_slider_4.setText(_translate("MainWindow", "0"))
        self.lnEdit_gain_slider_4.setText(_translate("MainWindow", "0"))
        self.label_slider5.setText(_translate("MainWindow", "Slider 5"))
        self.lnEdit_freq_slider_5.setText(_translate("MainWindow", "0"))
        self.lnEdit_gain_slider_5.setText(_translate("MainWindow", "0"))
        self.label_slider6.setText(_translate("MainWindow", "Slider 6"))
        self.lnEdit_freq_slider_6.setText(_translate("MainWindow", "0"))
        self.lnEdit_gain_slider_6.setText(_translate("MainWindow", "0"))
        self.label_slider7.setText(_translate("MainWindow", "Slider 7"))
        self.lnEdit_freq_slider_7.setText(_translate("MainWindow", "0"))
        self.lnEdit_gain_slider_7.setText(_translate("MainWindow", "0"))
        self.label_slider8.setText(_translate("MainWindow", "Slider 8"))
        self.lnEdit_freq_slider_8.setText(_translate("MainWindow", "0"))
        self.lnEdit_gain_slider_8.setText(_translate("MainWindow", "0"))
        self.label_slider9.setText(_translate("MainWindow", "Slider 9"))
        self.lnEdit_freq_slider_9.setText(_translate("MainWindow", "0"))
        self.lnEdit_gain_slider_9.setText(_translate("MainWindow", "0"))
        self.label_slider10.setText(_translate("MainWindow", "Slider 10"))
        self.lnEdit_freq_slider_10.setText(_translate("MainWindow", "0"))
        self.lnEdit_gain_slider_10.setText(_translate("MainWindow", "0"))
        self.lbl_speed.setText(_translate("MainWindow", "x1.0"))
        self.cmbx_mode_selection.setItemText(0, _translate("MainWindow", "Uniform Range Mode"))
        self.cmbx_mode_selection.setItemText(1, _translate("MainWindow", "Musical Instruments Mode"))
        self.cmbx_mode_selection.setItemText(2, _translate("MainWindow", "Animal Sounds Mode"))
        self.cmbx_mode_selection.setItemText(3, _translate("MainWindow", "ECG Abnormalities Mode"))
        self.grpbx_input.setTitle(_translate("MainWindow", "Input Signal"))
        self.grpbx_output.setTitle(_translate("MainWindow", "Output Signal"))
        self.chkbx_spect.setText(_translate("MainWindow", "Spectrogram"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
